/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CampaignIndexRouteImport } from './routes/campaign.index'
import { Route as CampaignCollectionRouteImport } from './routes/campaign.collection'
import { Route as CampaignDesignSystemRouteImport } from './routes/campaign.design-system'
import { Route as CampaignGrandPrizeRouteImport } from './routes/campaign.grand-prize'
import { Route as CampaignHomeRouteImport } from './routes/campaign.home'
import { Route as CampaignMapRouteImport } from './routes/campaign.map'
import { Route as CampaignPassportRouteImport } from './routes/campaign.passport'
import { Route as CampaignProfileRouteImport } from './routes/campaign.profile'
import { Route as CampaignRewardRouteImport } from './routes/campaign.reward'
import { Route as CampaignScanRouteImport } from './routes/campaign.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignCollectionRoute = CampaignCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignDesignSystemRoute = CampaignDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignGrandPrizeRoute = CampaignGrandPrizeRouteImport.update({
  id: '/grand-prize',
  path: '/grand-prize',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignHomeRoute = CampaignHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignMapRoute = CampaignMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignPassportRoute = CampaignPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignProfileRoute = CampaignProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignRewardRoute = CampaignRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignScanRoute = CampaignScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => CampaignRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/campaign/collection': typeof CampaignCollectionRoute
  '/campaign/design-system': typeof CampaignDesignSystemRoute
  '/campaign/grand-prize': typeof CampaignGrandPrizeRoute
  '/campaign/home': typeof CampaignHomeRoute
  '/campaign/map': typeof CampaignMapRoute
  '/campaign/passport': typeof CampaignPassportRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/reward': typeof CampaignRewardRoute
  '/campaign/scan': typeof CampaignScanRoute
  '/campaign/': typeof CampaignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign/collection': typeof CampaignCollectionRoute
  '/campaign/design-system': typeof CampaignDesignSystemRoute
  '/campaign/grand-prize': typeof CampaignGrandPrizeRoute
  '/campaign/home': typeof CampaignHomeRoute
  '/campaign/map': typeof CampaignMapRoute
  '/campaign/passport': typeof CampaignPassportRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/reward': typeof CampaignRewardRoute
  '/campaign/scan': typeof CampaignScanRoute
  '/campaign': typeof CampaignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/campaign/collection': typeof CampaignCollectionRoute
  '/campaign/design-system': typeof CampaignDesignSystemRoute
  '/campaign/grand-prize': typeof CampaignGrandPrizeRoute
  '/campaign/home': typeof CampaignHomeRoute
  '/campaign/map': typeof CampaignMapRoute
  '/campaign/passport': typeof CampaignPassportRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/reward': typeof CampaignRewardRoute
  '/campaign/scan': typeof CampaignScanRoute
  '/campaign/': typeof CampaignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/campaign/collection'
    | '/campaign/design-system'
    | '/campaign/grand-prize'
    | '/campaign/home'
    | '/campaign/map'
    | '/campaign/passport'
    | '/campaign/profile'
    | '/campaign/reward'
    | '/campaign/scan'
    | '/campaign/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign/collection'
    | '/campaign/design-system'
    | '/campaign/grand-prize'
    | '/campaign/home'
    | '/campaign/map'
    | '/campaign/passport'
    | '/campaign/profile'
    | '/campaign/reward'
    | '/campaign/scan'
    | '/campaign'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/campaign/collection'
    | '/campaign/design-system'
    | '/campaign/grand-prize'
    | '/campaign/home'
    | '/campaign/map'
    | '/campaign/passport'
    | '/campaign/profile'
    | '/campaign/reward'
    | '/campaign/scan'
    | '/campaign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/collection': {
      id: '/campaign/collection'
      path: '/collection'
      fullPath: '/campaign/collection'
      preLoaderRoute: typeof CampaignCollectionRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/design-system': {
      id: '/campaign/design-system'
      path: '/design-system'
      fullPath: '/campaign/design-system'
      preLoaderRoute: typeof CampaignDesignSystemRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/grand-prize': {
      id: '/campaign/grand-prize'
      path: '/grand-prize'
      fullPath: '/campaign/grand-prize'
      preLoaderRoute: typeof CampaignGrandPrizeRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/home': {
      id: '/campaign/home'
      path: '/home'
      fullPath: '/campaign/home'
      preLoaderRoute: typeof CampaignHomeRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/map': {
      id: '/campaign/map'
      path: '/map'
      fullPath: '/campaign/map'
      preLoaderRoute: typeof CampaignMapRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/passport': {
      id: '/campaign/passport'
      path: '/passport'
      fullPath: '/campaign/passport'
      preLoaderRoute: typeof CampaignPassportRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/profile': {
      id: '/campaign/profile'
      path: '/profile'
      fullPath: '/campaign/profile'
      preLoaderRoute: typeof CampaignProfileRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/reward': {
      id: '/campaign/reward'
      path: '/reward'
      fullPath: '/campaign/reward'
      preLoaderRoute: typeof CampaignRewardRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/scan': {
      id: '/campaign/scan'
      path: '/scan'
      fullPath: '/campaign/scan'
      preLoaderRoute: typeof CampaignScanRouteImport
      parentRoute: typeof CampaignRoute
    }
  }
}

interface CampaignRouteChildren {
  CampaignCollectionRoute: typeof CampaignCollectionRoute
  CampaignDesignSystemRoute: typeof CampaignDesignSystemRoute
  CampaignGrandPrizeRoute: typeof CampaignGrandPrizeRoute
  CampaignHomeRoute: typeof CampaignHomeRoute
  CampaignMapRoute: typeof CampaignMapRoute
  CampaignPassportRoute: typeof CampaignPassportRoute
  CampaignProfileRoute: typeof CampaignProfileRoute
  CampaignRewardRoute: typeof CampaignRewardRoute
  CampaignScanRoute: typeof CampaignScanRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteChildren: CampaignRouteChildren = {
  CampaignCollectionRoute: CampaignCollectionRoute,
  CampaignDesignSystemRoute: CampaignDesignSystemRoute,
  CampaignGrandPrizeRoute: CampaignGrandPrizeRoute,
  CampaignHomeRoute: CampaignHomeRoute,
  CampaignMapRoute: CampaignMapRoute,
  CampaignPassportRoute: CampaignPassportRoute,
  CampaignProfileRoute: CampaignProfileRoute,
  CampaignRewardRoute: CampaignRewardRoute,
  CampaignScanRoute: CampaignScanRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteWithChildren = CampaignRoute._addFileChildren(
  CampaignRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
